system:
  name: atomic
  training:
    collection_type: static
    n_configs: 1
    config:
      symbol: Be

  validation:
    collection_type: static
    n_configs: 1
    total_samples: 1000000
    config:
      symbol: Be