system:
  name: atomic
  training:
    collection_type: dynamic
    n_configs: 1
    config:
      symbol: Cr

  validation:
    collection_type: static
    n_configs: 1
    total_samples: 100000
    config:
      symbol: Cr