system:
  name: h2o
  training:
    collection_type: static
    n_configs: 1
    config:
      theta: 104.5
      R: 1.81035763

  validation:
    collection_type: static
    n_configs: 1
    total_samples: 1000000
    config:
      theta: 104.5
      R: 1.81035763
