seml:
    executable: /nfs/homedirs/qian/pesnet/train.py
    name: qcd_ma
    output_dir: /nfs/homedirs/qian/pesnet/seml_logs
    project_root_dir: /nfs/homedirs/qian/pesnet

slurm:
    experiments_per_job: 1
    sbatch_options:
        gres: gpu:1       # num GPUs
        mem: 12G          # memory
        cpus-per-task: 1  # num cores
        time: 14-00:00     # max time, D-HH:MM
        partition: gpu_large
        exclude: gpu15,gpu16,gpu17,gpu20

fixed:
    sampling:
        init_width: 0.02
        steps: 40

    optimization:
        aux_loss_weight: 1.e-3
        optimizer: sgd+clip
        clip_local_energy: 5.0
        clipping_method: ferminet
        gradient: natural
        max_norm: 1.0
        accumulate_n: 1
        lr:
            init: 1.e-1
            decay: 1.0
            delay: 1000.0
            gnn_prefactor: 1.0
        cg:
            damping:
                method: std_based
                init: 1.e-3
                schedule:
                    delay: 1000.0
                    decay: 1.0
                    min: 1.e-5
                    schedule: hyperbola
                adaptive:
                    step_size: 0.5
                    test_every: 50
                    threshold: 1.e-4
                std_based:
                    # base: 1.e-4
                    # base: 3.e-4
                    base: 1.e-3
            maxiter: 100
            precondition: False

    training:
        batch_size: 4096
        val_batch_size: 4096
        thermalizing_steps: 500
        checkpoint_every: 1000
        max_steps: 50000
        patience: 10000
        ema: 0.99
        eps: 0.001

    pretraining:
        steps: 2000
        single: False
        restricted: True
        lr: 0.0003

    pretrain_gnn: False

    pesnet:
        full_det: False
        envelope_type: 'isotropic'
        gnn_params:
            layers: [[32, 64], [32, 64]]
            embedding_dim: 64
            out_mlp_depth: 2
            use_pos_encoding: True
            pos_encoding_config:
                cutoff: 5.
                n_sph: 7
                n_rad: 6
            activation: silu

        model_type: trans

        trans_params:
            determinants: 16
            h_one_act: 'tanh'
            h_two_act: 'tanh'
            hidden_act: 'silu'
            nuclei_embedding: 32
            input_mlp_dims: [32, 32]
            att_hidden_size_v: 256
            att_hidden_size_qk: 64
            ee_readout_size: 32    # htwo info readout -> concat with hone
            num_attention_heads: 4
            # QK_init_scale: 0.3
            ee_attention: False
            intermediate_size: 256
            ee_intermediate_size: 32  # h-two update
            num_hidden_layers: 3

        # https://gitlab.lrz.de/ge69bec/pesnet/-/blob/flax/configs/pesnet.yaml
        global_filter: {}
        node_filter: {}
        include_default_filter: False
        meta_network: gnn

grid:
    # seed:
    #     type: choice
    #     options:
    #         - 12221
    #         - 37446
    #         - 84364
    #         - 82454
    #         - 57659
    #         - 21172
    #         - 48204
    #         - 31102
    #         - 71802
    #         - 88949

    pesnet.trans_params.QK_init_scale: 
        type: choice
        options:
            # - 0.01
            # - 0.03
            # - 0.05
            - 0.07
            # - 0.1
            # - 0.3
            # - 0.5
            # - 0.7
        
    # pesnet.trans_params.num_attention_heads:
    #     type: choice
    #     options:
    #         - 4
    #         - 8
    #         - 16
